### ISSUE TITLE
Generating New Address and Dumping Private Key Fails

### ISSUE THREAD

**Issue by AlphaSerpentis** [beyondcoin-project/beyondcoin#11]
**Expected Behavior**

Generate a public address, and then being able to dump the private keys for it via `beyondcoin-cli dumpprivkey [addr]`

**Actual Behavior**

Unable to dump the private key, the client was thrown:

`error code: -4
error message:
Private key for address [addr] is not known`

**To Reproduce**

1.) Run `beyondcoin-cli getnewaddress`
2.) Copy the generated address
3.) Run `beyond-cli dumpprivkey [copied address]`

**System Information**

- Linux x86-64 (Ubuntu 18.04)
- 2 vCPU
- 1 GB of RAM, 4 GB of Swap Memory
- 325 GB HDD

Latest Release (Beyondcoin Core Daemon version v0.16.3.0-900277e-dirty)

**Comment by Myke500** [comment]
As explained by chaozer the keys are the same and need to differ.  See my PR

**Comment by Tech1k** [comment]
Fixed by: 735e812
