### ISSUE TITLE
Checkpoint numbers should be = to difficulty retarget values

### ISSUE THREAD

**Issue by jakesum** [beyondcoin-project/beyondcoin#6]
Currently you have checkpoints done incorrectly as .....

Missing block 0
intervals are incorrect

Should be like in read me
"Difficulty Adjustment Interval | 8064 Blocks"

Go to https://github.com/jakesum/beyondcoin/blob/v0.16/src/chainparams.cpp

Example

checkpointData = {
            {
                { 0, uint256S("GenesisHashHerexxxxxxxxxjkxjockjsdbclkcjbsdcl")},
                { 8064, uint256S("Block8064HashHerexxxxxxxxxxlkfjhlf")},
 and so on....  but keep the block intervals for next checkpoints equal to 8064 spacing.   that could be 8064x5 or 8064x10.   Doesnt matter.   Just needs to have genesis "0" and every interval thereafter should be equal to deedle difficulty retargeting block value (8064)

**Comment by Tech1k** [comment]
Thank you for letting me know! I've committed a fix to this, for the first 10 checkpoints, it's every 2,016 blocks and after that, it's every 8,064 blocks so we don't have too many checkpoints.
